$(function(){$("#nav .hot_div").addClass("hot_div01").removeClass("hot_div");$("#nav .hot_div01 .other_div").css("height","320px");$("#nav .hot_div01 .other_div .box_ul").show();function gallery(){var $this=$("#banner .img_list");var len=$this.children("li").length;var iNow=0;var times=null;autoPlay();var prev=$this.parents("div").find(".banner_prev");var next=$this.parents("div").find(".banner_next");function autoPlay(){times=setInterval(function(){iNow++;change(iNow);},5000);};function change(num){if(num>len-1){num=0;iNow=num;}
if(num<0){num=len-1;iNow=num;}
$this.stop(true);$this.find("li").siblings().stop().animate({opacity:0},500).css("z-index",1).end().eq(num).stop().animate({opacity:1},800).css("z-index",2);$this.next(".banner_focus").find("a").eq(num).addClass("on").siblings().removeClass("on");};$this.parent(".banner_box").mouseenter(function(){clearInterval(times);prev.show();next.show();}).mouseleave(function(){autoPlay();prev.hide();next.hide();});prev.click(function(){iNow--;change(iNow);});next.click(function(){iNow++;change(iNow);});$(".banner_focus a").each(function(i){$(this).mouseover(function(){iNow=i;change(i);});});}gallery();(function(){var $this=$("#banner .box3 ul");var h=$this.children("li").eq(0).height();var oli=$this.children("li").eq(0).clone(true);$this.append(oli);var len=$this.children("li").length;$this.css("height",len*h);var iNow=0;var times=null;autoPlay();var prev=$("#banner .box3 .prev");var next=$("#banner .box3 .next");function autoPlay(){times=setInterval(function(){iNow++;move(iNow);},5000);};function move(num){if(num>len-1){$this.css("top",0);num=1;iNow=num;}
if(num<0){$this.css("top",-((len-1)*h));num=len-1;iNow=num;}
$this.stop(true);$this.animate({"top":-(num*h)},600);};$this.parents(".box3").mouseover(function(){clearInterval(times);}).mouseout(function(){autoPlay();});prev.click(function(){iNow--;move(iNow);});next.click(function(){iNow++;move(iNow);});}());(function(){var listLi=$("#today_focus .list li");listLi.eq(-1).css("margin-right",0);var listLiLength=listLi.length
var ulWidth=0;for(var i=0;i<listLiLength;i++){var liWidth=Math.ceil(listLi.eq(i).outerWidth(true));ulWidth+=liWidth;}
$("#today_focus .list ul").width(ulWidth+1);$("#today_focus .next").click(function(){$("#today_focus .list ul").animate({"left":1010-ulWidth},500)});$("#today_focus .prev").click(function(){$("#today_focus .list ul").animate({"left":0},500)});$("#today_focus .box").mouseenter(function(){$(this).find(".next,.prev").show();}).mouseleave(function(){$(this).find(".next,.prev").hide();});}());(function(){var $box3=$("#floor1 .box3");$box3.find(".more_span").on("mouseenter",function(){$box3.find(".more_div").show();}).on("mouseleave",function(){$box3.find(".more_div").hide();});$box3.find(".more_div li").each(function(i){$(this).click(function(){var liText=$(this).html();$box3.find(".more_span .text").html(liText);$box3.find(".content").hide().addClass("o").removeClass("o");$box3.find(".content").eq(i).show();});});}());$("#floor1 .box3 .open_link").each(function(){$(this).on("mouseenter",function(){$(this).prepend('<div class="hover"></div>');}).on("mouseleave",function(){$(this).find(".hover").remove();});});$("#floor1 .box3 .content").each(function(){$(this).find(".open_link").eq(-1).addClass("no_bd")})
function createQueryStr04($target){var queryStr=[];$.each(["material","manufacturer"],function(i,item){queryStr.push([encodeURIComponent($.trim($target.data(item)))]);});return queryStr.join("_");};$(document).on("click","#floor1 .box3 .open_link",function(e){window.open(HQ_URL+"price/0_1_"+ createQueryStr04($(this))+"_0_1_0_0.html");});var slideMenu=function(){var sp,st,t,m,sa,l,w,sw,ot;return{build:function(sm,sw,mt,s,sl,h){sp=s;st=sw;t=mt;m=document.getElementById(sm);sa=m.getElementsByTagName('li');l=sa.length;w=m.offsetWidth;sw=w/l;ot=Math.floor((w- st)/ (l - 1));
var i=0;for(i;i<l;i++){s=sa[i];s.style.width=sw+'px';this.timer(s)}
if(sl!=null){m.timer=setInterval(function(){slideMenu.slide(sa[sl- 1])},t)}},timer:function(s){s.onmouseover=function(){clearInterval(m.timer);m.timer=setInterval(function(){slideMenu.slide(s)},t)}},slide:function(s){var cw=parseInt(s.style.width,'10');if(cw<st){var owt=0;var i=0;for(i;i<l;i++){if(sa[i]!=s){var o,ow;var oi=0;o=sa[i];ow=parseInt(o.style.width,'10');if(ow>ot){oi=Math.floor((ow- ot)/ sp);
oi=(oi>0)?oi:1;o.style.width=(ow- oi)+'px'}
owt=owt+(ow- oi)}}
s.style.width=(w- owt)+'px';$(s).siblings().removeClass('active');$(s).addClass('active');}else{clearInterval(m.timer)}}};}();slideMenu.build('slide_menu',360,15,15,1);function createQueryStr02($target){var queryStr=[];$.each(["cate","material","manufacturer"],function(i,item){queryStr.push([item,encodeURIComponent($.trim($target.data(item)))].join("="));});return queryStr.join("&");};$(document).on("click","#floor2 .open_link",function(e){window.open("http://"+window.location.host+"/product/list?dayCon=-30&"+ createQueryStr02($(this)));});$("#floor2 .box2 .content1 .open_link").each(function(){$(this).on("mouseenter",function(){$(this).prepend('<div class="hover"></div>');}).on("mouseleave",function(){$(this).find(".hover").remove();});});$("#recent_trade1").scrollcontent(50);$("#recent_trade2").scrollcontent(50);$("#recent_trade3").scrollcontent(50);$("#floor2").find(".box2 .tab_title li").each(function(i){$(this).mouseenter(function(){$("#floor2 .box2 .tab_title li").removeClass("on");$(this).addClass("on");$("#floor2 .box2 .content").hide().addClass("o");$("#floor2 .box2 .content").eq(i).show().removeClass("o");});});$("#floor2 .content2").on('mousemove','td.w2a',function(ev){var str=$(this).parent().find('span').html();$("#tip_message").show();$("#tip_message").html(str);var t=$(window).scrollTop();var x=ev.clientX+20;var y=ev.clientY+t-15;$("#tip_message").css({left:x,top:y});});$("#floor2 .content2").on('mouseout','td.w2a',function(ev){$("#tip_message").hide();});$("#floor3 .box2 .content li").eq(-1).addClass("noborder");$("#floor3 .box2 .content li").eq(-2).addClass("noborder");$("#floor3 .box2 .content li:odd").addClass("odd");$.fn.scrollcontent1=function(interval){var $this=$(this);var box=$this.closest("div")
var m=box.height();var n=$this.height();var oneHeight=$this.children("li").eq(0).height();var len=Math.round($this.children("li").length);if(n>=m){$this.append($this.html());var iNum=0;var timer;var start=function(){timer=setInterval(function(){iNum++;if(iNum>len){$this.css("top",0);iNum=1;}
$this.animate({"top":-iNum*oneHeight},400);},interval);}
var stop=function(){clearInterval(timer);}
start();box.on("mouseover",stop).on("mouseout",start);}};$("#floor5 .entrust_list ul").scrollcontent1(1000);$("#floor6 .live_div .intercept_text").each(function(){$(this).interceptText(26);});$("#floor6 .img_div .intercept_text").each(function(){$(this).interceptText(18);});$("#floor6 .article_list .intercept_text").each(function(){$(this).interceptText(76);});$("#floor6 .voice .intercept_text01 a").each(function(){$(this).interceptText(34);});$("#floor6 .voice .intercept_text02").each(function(){$(this).interceptText(28);});(function(){var times=null;var index=0;function tab(index){$("#floor6 .img_div .tab_title li").removeClass("on");$("#floor6 .img_div .tab_title li").eq(index).addClass("on");$("#floor6 .img_div .content").hide();$("#floor6 .img_div .content").eq(index).show();}
function time_satrt(){times=setInterval(function(){index++;if(index>$("#floor6 .img_div .tab_title li").length-1){index=0;};if(index<0){index=$("#floor6 .img_div .tab_title li").length-1;}
tab(index)},4000);}
time_satrt();$("#floor6 .img_div").mouseover(function(){clearInterval(times);}).mouseout(function(){clearInterval(times);time_satrt();});$("#floor6 .img_div .tab_title li").each(function(i){$(this).mouseover(function(){$("#floor6 .img_div .tab_title li").removeClass("on");$(this).addClass("on");$("#floor6 .img_div .content").hide();$("#floor6 .img_div .content").eq(i).show();index=i;});});}());(function(){$("#floor6 .article_list li .p2").each(function(){var tag=$(this).data("tag");var arr=tag.split(" ");if(tag){for(var i=0;i<arr.length;i++){var tagHtml=arr[i];$(this).append('<a class="tag" href="'+HQ_URL+'kw/'+tagHtml+'.html" target="_blank">'+tagHtml+'</a>')}}})
$("#floor6 .article_list li").eq(-1).css("border-bottom","none")}());(function(){$("#floor6 .voice .p1").each(function(){var tag=$(this).data("tag");if(tag){var arr=tag.split(" ");for(var i=0;i<arr.length;i++){var tagHtml=arr[i];$(this).append('<a class="tag" href="'+HQ_URL+'kw/'+tagHtml+'.html" target="_blank">'+tagHtml+'</a>')}}})
$("#floor6 .voice li").eq(-1).css("border-bottom","none")}());var lift={pos:{},get_pos:function(){$("body").find(".floor").each(function(index){lift.pos[index]=$(this).offset().top;});},style:function(index){var $this=$("#lift ul").find("li").eq(index);$this.addClass("on").siblings("li").each(function(){$(this).removeClass("on");});},go:function(){$("#lift ul").find("li").on("click",function(){$(window).off("scroll",lift.scroll);var index=$(this).index();$("html,body").animate({scrollTop:lift.pos[index]-200},500,function(){lift.style(index);$(window).on("scroll",lift.scroll);});});},scroll:function(){var s_top=$(window).scrollTop();if(s_top>lift.pos[0]-100){$("#lift").fadeIn(500);var n=$("#lift ul").find("li").length;for(i=0;i<n;i++){if($("body").find(".floor").eq(i).offset().top-200<=s_top){lift.style(i);};};}else{$("#lift").fadeOut(500);}},init:function(){lift.get_pos();lift.go();$(window).on("scroll",lift.scroll);}};lift.init();});